const DRILL_LIBRARY = {
  FS: [
    { name: 'Single Arm with Float — Buoyancy', type: 'drill', kickPct: 30, paceFactor: 1.667, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "Encourage the swimmer to use buoyancy to float and breathe instead of pushing down on the water. Beginning of a progression leading to Single Arm (Buoyancy) without float.",
      technique: "Place the leading hand flat on a small float, fingers spread wide, arm straight in front and in line. Swim with the other arm, breathing to the side of the active arm. Push ribs into the water and toward the chin to use the lungs as buoyancy. When rotated, activate lower traps to externally rotate the shoulders. Swap arms every length.",
      coachingNotes: "The float should stay flat — not swing side to side, front and back level, not pushed down. The swimmer should almost imagine lifting the hand above the float. If buoyancy is not being used, the float will tilt or sink when breathing. Cue: imagine tightening your belt to control core and alignment.",
      url: null },
    { name: 'Single Arm with Float — Catch', type: 'drill', kickPct: 30, paceFactor: 1.667, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "Isolate the arm to develop the feel and muscle memory for a high elbow catch (EVF).",
      technique: "As Single Arm with Float (Buoyancy) but after entering and reaching forward, concentrate on keeping the elbow high and dropping the fingertips to gain the EVF position.",
      coachingNotes: "Ensure the swimmer rotates and engages the lats so the propulsive arm stays to the side of the body.",
      url: null },
    { name: 'Single Arm with Float — Pull', type: 'drill', kickPct: 30, paceFactor: 1.667, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "Learn to feel the water and sense the weight building in the hand as the arm accelerates through the pull.",
      technique: "Single arm freestyle concentrating on a bent arm pull and accelerating the hand speed as it moves through the water.",
      coachingNotes: "",
      url: null },
    { name: 'Single Arm with Float — Finish', type: 'drill', kickPct: 30, paceFactor: 1.667, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "Hold onto the work and exit cleanly.",
      technique: "Single arm freestyle concentrating on pushing the water past the hip, keeping the fingers pointing down while holding pressure on the water, then exiting by lifting the elbow using the thoracic and shoulder muscles.",
      coachingNotes: "",
      url: null },
    { name: 'Single Arm — Counter-rotation', type: 'drill', kickPct: 40, paceFactor: 1.667, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "Learn to use the serape effect to develop a sharper acceleration with the working arm.",
      technique: "Single arm freestyle, lazy arm out front or by the side. Reach with the working arm and rotate to the opposite side while reaching. As the catch is initiated, rotate the working arm\'s hip up using a strong downbeat kick on that side to lift the hip and engage the serape effect.",
      coachingNotes: "",
      url: 'https://www.youtube.com/watch?v=S0ruyow45WE' },
    { name: 'Single Arm — Rotation Timing', type: 'drill', kickPct: 40, paceFactor: 1.667, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "Time the rotation and kick with the arms — downbeat kick occurs as the hand goes through the catch.",
      technique: "Single arm freestyle, lazy arm out front or by the side. Concentrate on ensuring the downbeat kick occurs as the hand goes through the catch. This will lift the hip and commence body rotation.",
      coachingNotes: "",
      url: null },
    { name: 'Single Arm — Buoyancy', type: 'drill', kickPct: 40, paceFactor: 1.667, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "Encourage use of buoyancy to float and breathe without pushing down on the water. Progression from Single Arm with Float (Buoyancy).",
      technique: "Lazy arm\'s hand out in front, palm down at the surface, straight in front and in line. Swim with the other arm breathing to the side of the active arm. Push ribs into the water toward the chin. Activate lower traps to externally rotate shoulders when rotated. Swap arms every length.",
      coachingNotes: "The hand should stay flat on the water and not swing side to side. The swimmer should lift the leading hand to breathe. Cue: tighten your belt to control core and alignment.",
      url: null },
    { name: 'Swordfish — Balance', type: 'drill', kickPct: 100, paceFactor: 2.5, zoneCeiling: 'A3', isDurationBased: false, applicableStrokes: null,
      objective: "Develop body control and balance.",
      technique: "Top arm still with hand in pocket position. Lower arm outstretched in front, inline with body, palm facing down, shoulder externally rotated using lower traps and rhomboids. Face in the water looking straight down, deltoid of top arm pressed against cheek. Externally rotate upper arm and use lower traps to pull the upper arm\'s shoulder away from the ear. Breathe by turning the head sideways with minimal movement elsewhere.",
      coachingNotes: "Most importantly the lower arm\'s hand must not sink when breathing — keep it on the surface by pressing the ribs up away from the waist as if tightening your belt.",
      url: null },
    { name: 'Swordfish — Streamline', type: 'drill', kickPct: 100, paceFactor: 2.5, zoneCeiling: 'A3', isDurationBased: false, applicableStrokes: null,
      objective: "Develop a good streamline position just as and after the hand enters.",
      technique: "As Swordfish (Balance). Focus on the position of the lead arm at entry — pressing into streamline.",
      coachingNotes: "",
      url: null },
    { name: 'Swordfish — Rotation', type: 'drill', kickPct: 100, paceFactor: 2.5, zoneCeiling: 'A3', isDurationBased: false, applicableStrokes: null,
      objective: "By over-rotating, helps the swimmer reach an appropriate rotation when swimming full stroke.",
      technique: "As Swordfish (Balance). Exaggerate the rotation to each side to develop body awareness of full rotation range.",
      coachingNotes: "",
      url: null },
    { name: 'Shark Fin — Balance', type: 'drill', kickPct: 100, paceFactor: 2.5, zoneCeiling: 'A3', isDurationBased: false, applicableStrokes: null,
      objective: "Advancement on Swordfish with harder demands on balance and control. Reinforces high elbow recovery.",
      technique: "Do not use until Swordfish is done well. Identical to Swordfish except the upper arm moves slowly and under control from hand-in-pocket position to thumb-in-armpit position with elbow pointing directly upwards.",
      coachingNotes: "This is harder than Swordfish — control and balance demands are significantly increased.",
      url: null },
    { name: 'Double Tap', type: 'drill', kickPct: 70, paceFactor: 2.5, zoneCeiling: 'A2', isDurationBased: false, applicableStrokes: null,
      objective: "Develop core stability and balance and get the armpit out of the water.",
      technique: "Leave the front arm high. Let the recovering arm come high over the top to recover but just touch the inside of the elbow with the recovering fingertips. Then take the recovering arm all the way back to the hip, recover normally and take a stroke to swap arms.",
      coachingNotes: "",
      url: null },
    { name: '12-3-12', type: 'drill', kickPct: 60, paceFactor: 2.0, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "Develop core stability, balance and timing.",
      technique: "From swordfish take 12 kicks, then three strokes back to swordfish with the other arm. Repeat.",
      coachingNotes: "",
      url: null },
    { name: 'Catch Up', type: 'drill', kickPct: 40, paceFactor: 1.667, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "Develop front quadrant swimming and control.",
      technique: "Leave one hand out in front until the other hand touches it. Only then can it take a stroke while the just-recovered hand waits to be tagged before moving.",
      coachingNotes: "Be aware: too much catch-up can promote lack of rotation.",
      url: null },
    { name: '3/4 Catch Up', type: 'drill', kickPct: 30, paceFactor: 1.667, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "Develop timing. A difficult enhancement of Catch Up.",
      technique: "As Catch Up but the recovering hand comes only to just above the head. At this point it pauses for two kicks, then in one movement: the hand out front begins the catch, the same-side leg kicks down hard, the recovering arm spears the water, and the working-side hip begins to rise.",
      coachingNotes: "",
      url: null },
    { name: 'Thumbs / Zipper', type: 'drill', kickPct: 30, paceFactor: 1.667, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "Develop high elbow recovery by dragging the thumb up the side of the body.",
      technique: "During recovery, drag the thumb up the side of the body from hip to armpit before extending forward.",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'Fingernail Trail', type: 'drill', kickPct: 20, paceFactor: 1.667, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "Develop control and help the swimmer find the optimum entry point.",
      technique: "Trail the fingernails along the surface of the water during recovery, entering at the optimum point.",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'One Eye Closed', type: 'drill', kickPct: 0, paceFactor: 1.25, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "Help stop the swimmer from lifting or turning the head too much when breathing.",
      technique: "Full stroke freestyle. Close one eye — if the head is lifting or over-rotating the closed eye will see air. The open eye should remain in the water throughout the breath.",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'DPS', type: 'drill', kickPct: 0, paceFactor: 1.25, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "Help the swimmer establish optimum stroke length and acceleration.",
      technique: "Count strokes per length. Focus on maximising distance per stroke while maintaining acceleration through the pull.",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'Freestyle with Fly Kick', type: 'drill', kickPct: 0, paceFactor: 1.429, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "Help with kick timing and progress toward a two-beat kick.",
      technique: "Full freestyle arm action with butterfly kick instead of flutter kick.",
      coachingNotes: "detail_pending",
      url: null },
    { name: '2 Beat Kick', type: 'drill', kickPct: 0, paceFactor: 1.111, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "Develop kick timing. Suitable for distance swimmers.",
      technique: "One kick per arm stroke (two kicks per cycle) co-ordinated with body rotation.",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'Breathing Drills', type: 'drill', kickPct: 0, paceFactor: 1.111, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "Build better breath control.",
      technique: "detail_pending",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'Extended Doggy Paddle / Long Dog', type: 'drill', kickPct: 30, paceFactor: 2.0, zoneCeiling: 'A2', isDurationBased: false, applicableStrokes: null,
      objective: "detail_pending",
      technique: "detail_pending",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'Half Dog', type: 'drill', kickPct: 30, paceFactor: 2.5, zoneCeiling: 'A2', isDurationBased: false, applicableStrokes: null,
      objective: "detail_pending",
      technique: "detail_pending",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'Bow and Arrow', type: 'drill', kickPct: 40, paceFactor: 1.667, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "detail_pending",
      technique: "detail_pending",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'Paddle Head', type: 'drill', kickPct: 0, paceFactor: 1.667, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "detail_pending",
      technique: "detail_pending",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'Double Look', type: 'drill', kickPct: 40, paceFactor: 2.5, zoneCeiling: 'A2', isDurationBased: false, applicableStrokes: null,
      objective: "Develop quick, efficient breath.",
      technique: "Swim in swordfish position then turn the head so the back of the head touches the bicep — twice. The swimmer should create a quick air pocket to breathe. As soon as the second look is done, take a stroke to swap arms. Fins or fast kick required.",
      coachingNotes: "",
      url: 'https://www.youtube.com/watch?v=jXYxVnjB7Ko' },
    { name: 'Early Breathing', type: 'focus', kickPct: 0, paceFactor: 1.111, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "Get the head straight earlier after breathing.",
      technique: "Full stroke FS. Focus on returning the head to neutral position before the recovering arm enters.",
      coachingNotes: "",
      url: null },
    { name: 'Push the Finish', type: 'focus', kickPct: 0, paceFactor: 1.0, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "Maintain power through the full arm cycle to the finish.",
      technique: "Full stroke FS. Focus on pushing water all the way past the hip before beginning recovery.",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'High Elbow Finish', type: 'focus', kickPct: 0, paceFactor: 1.0, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "Clean exit using thoracic and shoulder muscles.",
      technique: "Full stroke FS. Focus on lifting the elbow using thoracic and shoulder muscles at exit.",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'Accelerate the Finish', type: 'focus', kickPct: 0, paceFactor: 1.0, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "Build hand speed through the final phase of the pull.",
      technique: "Full stroke FS. Focus on accelerating the hand from catch through to finish.",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'Fast Elbow Exit', type: 'focus', kickPct: 0, paceFactor: 1.0, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "Develop a fast, clean elbow exit to initiate recovery efficiently.",
      technique: "Full stroke FS. Focus on a quick elbow lift at exit.",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'High Elbow Entry', type: 'focus', kickPct: 0, paceFactor: 1.111, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "Ensure the hand enters with the elbow high to begin the catch correctly.",
      technique: "Full stroke FS. Focus on entering with elbow above the hand, fingertips first.",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'EVF / High Elbow Catch', type: 'focus', kickPct: 0, paceFactor: 1.111, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "Develop Early Vertical Forearm position to maximise propulsive surface area at catch.",
      technique: "Full stroke FS. Focus on dropping the fingertips immediately after entry so the forearm is vertical as early as possible.",
      coachingNotes: "detail_pending",
      url: null },
  ],
  BK: [
    { name: 'Streamline Kick', type: 'drill', kickPct: 100, paceFactor: 2.5, zoneCeiling: 'A3', isDurationBased: false, applicableStrokes: null,
      objective: "detail_pending",
      technique: "detail_pending",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'Cups', type: 'drill', kickPct: 20, paceFactor: 1.667, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "detail_pending",
      technique: "detail_pending",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'Single Arm', type: 'drill', kickPct: 40, paceFactor: 1.667, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "detail_pending",
      technique: "detail_pending",
      coachingNotes: "detail_pending",
      url: null },
    { name: '12-3-12 Rotation', type: 'drill', kickPct: 60, paceFactor: 2.0, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "detail_pending",
      technique: "detail_pending",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'Fly Kick on Back', type: 'drill', kickPct: 100, paceFactor: 2.5, zoneCeiling: 'A3', isDurationBased: false, applicableStrokes: null,
      objective: "detail_pending",
      technique: "detail_pending",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'Catch Up', type: 'drill', kickPct: 40, paceFactor: 1.667, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "detail_pending",
      technique: "detail_pending",
      coachingNotes: "detail_pending",
      url: null },
  ],
  BR: [
    { name: '2K1P', type: 'drill', kickPct: 60, paceFactor: 2.0, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "detail_pending",
      technique: "detail_pending",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'Heels to Hands on Back', type: 'drill', kickPct: 80, paceFactor: 2.5, zoneCeiling: 'A2', isDurationBased: false, applicableStrokes: null,
      objective: "detail_pending",
      technique: "detail_pending",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'Heels to Hands on Front', type: 'drill', kickPct: 80, paceFactor: 2.5, zoneCeiling: 'A2', isDurationBased: false, applicableStrokes: null,
      objective: "detail_pending",
      technique: "detail_pending",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'Streamline Kick', type: 'drill', kickPct: 100, paceFactor: 2.0, zoneCeiling: 'A3', isDurationBased: false, applicableStrokes: null,
      objective: "detail_pending",
      technique: "detail_pending",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'BR Arms Fly Legs', type: 'drill', kickPct: 50, paceFactor: 1.667, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "detail_pending",
      technique: "detail_pending",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'BR Arms Flutter Legs', type: 'drill', kickPct: 30, paceFactor: 1.429, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "detail_pending",
      technique: "detail_pending",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'Long Glide BR', type: 'drill', kickPct: 60, paceFactor: 2.0, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "detail_pending",
      technique: "detail_pending",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'Countdown and Back BR', type: 'drill', kickPct: 60, paceFactor: 2.0, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "detail_pending",
      technique: "detail_pending",
      coachingNotes: "detail_pending",
      url: null },
  ],
  Fly: [
    { name: 'Wrist Clap', type: 'drill', kickPct: 40, paceFactor: 2.0, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "detail_pending",
      technique: "detail_pending",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'Thumb Drag', type: 'drill', kickPct: 30, paceFactor: 1.667, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "detail_pending",
      technique: "detail_pending",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'Fly with Fins', type: 'drill', kickPct: 50, paceFactor: 1.25, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "detail_pending",
      technique: "detail_pending",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'Chest Pressing', type: 'drill', kickPct: 60, paceFactor: 2.0, zoneCeiling: 'A2', isDurationBased: false, applicableStrokes: null,
      objective: "detail_pending",
      technique: "detail_pending",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'LRF 3-3-3', type: 'drill', kickPct: 40, paceFactor: 2.0, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "detail_pending",
      technique: "detail_pending",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'Body Dolphin Hands in Pockets', type: 'drill', kickPct: 100, paceFactor: 3.333, zoneCeiling: 'A3', isDurationBased: false, applicableStrokes: null,
      objective: "detail_pending",
      technique: "detail_pending",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'Body Dolphin Hands Out Front', type: 'drill', kickPct: 100, paceFactor: 3.333, zoneCeiling: 'A3', isDurationBased: false, applicableStrokes: null,
      objective: "detail_pending",
      technique: "detail_pending",
      coachingNotes: "detail_pending",
      url: null },
    { name: '3K1P', type: 'drill', kickPct: 60, paceFactor: 2.0, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "detail_pending",
      technique: "detail_pending",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'Side Breath LRF', type: 'drill', kickPct: 40, paceFactor: 2.0, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "detail_pending",
      technique: "detail_pending",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'Fly with Flutter', type: 'drill', kickPct: 30, paceFactor: 1.429, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "detail_pending",
      technique: "detail_pending",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'Biondi Drill', type: 'drill', kickPct: 30, paceFactor: 1.667, zoneCeiling: null, isDurationBased: false, applicableStrokes: null,
      objective: "detail_pending",
      technique: "detail_pending",
      coachingNotes: "detail_pending",
      url: null },
  ],
  MULTI: [
    { name: 'Sculling — Front', type: 'drill', kickPct: 0, paceFactor: 3.333, zoneCeiling: 'A2', isDurationBased: false, applicableStrokes: null,
      objective: "Develop feel for the water and hand pressure. Teaches the swimmer to feel and manipulate the water with the hands.",
      technique: "Arms extended forward, hands sweeping in and out in a figure-8 pattern to generate forward propulsion. Body flat and streamlined.",
      coachingNotes: "Zone ceiling A2 — insufficient musculature engaged for AT or above.",
      url: null },
    { name: 'Sculling — Mid', type: 'drill', kickPct: 0, paceFactor: 3.333, zoneCeiling: 'A2', isDurationBased: false, applicableStrokes: null,
      objective: "Develop feel for water pressure through the mid-pull phase.",
      technique: "Arms at 90 degrees, hands sculling in figure-8 under the body.",
      coachingNotes: "detail_pending",
      url: null },
    { name: 'Sculling — Rear', type: 'drill', kickPct: 0, paceFactor: 3.333, zoneCeiling: 'A2', isDurationBased: false, applicableStrokes: null,
      objective: "Develop feel for the finish phase and backward sculling.",
      technique: "Arms by the sides, hands sculling to generate backward or forward movement.",
      coachingNotes: "detail_pending",
      url: null },
  ],
  COND: [
    { name: 'Vertical Kick', type: 'conditioning', kickPct: 100, paceFactor: null, zoneCeiling: null, isDurationBased: true, applicableStrokes: ["FS", "BK", "BR", "Fly"],
      objective: "Develop leg power, ankle flexibility and kick tempo. The 5th stroke.",
      technique: "Vertical position in deep water, arms crossed or by sides. Kick to maintain height. Can be done with hands above water to increase load.",
      coachingNotes: "One of the few drills that can be high intensity. Duration prescribed, not distance.",
      url: null },
  ],
};

export { DRILL_LIBRARY };
